/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/ishustava/k8s-credhub-controller/pkg/apis/credhubsecret/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// CredhubSecretLister helps list CredhubSecrets.
type CredhubSecretLister interface {
	// List lists all CredhubSecrets in the indexer.
	List(selector labels.Selector) (ret []*v1.CredhubSecret, err error)
	// CredhubSecrets returns an object that can list and get CredhubSecrets.
	CredhubSecrets(namespace string) CredhubSecretNamespaceLister
	CredhubSecretListerExpansion
}

// credhubSecretLister implements the CredhubSecretLister interface.
type credhubSecretLister struct {
	indexer cache.Indexer
}

// NewCredhubSecretLister returns a new CredhubSecretLister.
func NewCredhubSecretLister(indexer cache.Indexer) CredhubSecretLister {
	return &credhubSecretLister{indexer: indexer}
}

// List lists all CredhubSecrets in the indexer.
func (s *credhubSecretLister) List(selector labels.Selector) (ret []*v1.CredhubSecret, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.CredhubSecret))
	})
	return ret, err
}

// CredhubSecrets returns an object that can list and get CredhubSecrets.
func (s *credhubSecretLister) CredhubSecrets(namespace string) CredhubSecretNamespaceLister {
	return credhubSecretNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// CredhubSecretNamespaceLister helps list and get CredhubSecrets.
type CredhubSecretNamespaceLister interface {
	// List lists all CredhubSecrets in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1.CredhubSecret, err error)
	// Get retrieves the CredhubSecret from the indexer for a given namespace and name.
	Get(name string) (*v1.CredhubSecret, error)
	CredhubSecretNamespaceListerExpansion
}

// credhubSecretNamespaceLister implements the CredhubSecretNamespaceLister
// interface.
type credhubSecretNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all CredhubSecrets in the indexer for a given namespace.
func (s credhubSecretNamespaceLister) List(selector labels.Selector) (ret []*v1.CredhubSecret, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.CredhubSecret))
	})
	return ret, err
}

// Get retrieves the CredhubSecret from the indexer for a given namespace and name.
func (s credhubSecretNamespaceLister) Get(name string) (*v1.CredhubSecret, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("credhubsecret"), name)
	}
	return obj.(*v1.CredhubSecret), nil
}
