/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	credhubsecretv1 "github.com/ishustava/k8s-credhub-controller/pkg/apis/credhubsecret/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCredhubSecrets implements CredhubSecretInterface
type FakeCredhubSecrets struct {
	Fake *FakePivotalV1
	ns   string
}

var credhubsecretsResource = schema.GroupVersionResource{Group: "pivotal.io", Version: "v1", Resource: "credhubsecrets"}

var credhubsecretsKind = schema.GroupVersionKind{Group: "pivotal.io", Version: "v1", Kind: "CredhubSecret"}

// Get takes name of the credhubSecret, and returns the corresponding credhubSecret object, and an error if there is any.
func (c *FakeCredhubSecrets) Get(name string, options v1.GetOptions) (result *credhubsecretv1.CredhubSecret, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(credhubsecretsResource, c.ns, name), &credhubsecretv1.CredhubSecret{})

	if obj == nil {
		return nil, err
	}
	return obj.(*credhubsecretv1.CredhubSecret), err
}

// List takes label and field selectors, and returns the list of CredhubSecrets that match those selectors.
func (c *FakeCredhubSecrets) List(opts v1.ListOptions) (result *credhubsecretv1.CredhubSecretList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(credhubsecretsResource, credhubsecretsKind, c.ns, opts), &credhubsecretv1.CredhubSecretList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &credhubsecretv1.CredhubSecretList{ListMeta: obj.(*credhubsecretv1.CredhubSecretList).ListMeta}
	for _, item := range obj.(*credhubsecretv1.CredhubSecretList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested credhubSecrets.
func (c *FakeCredhubSecrets) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(credhubsecretsResource, c.ns, opts))

}

// Create takes the representation of a credhubSecret and creates it.  Returns the server's representation of the credhubSecret, and an error, if there is any.
func (c *FakeCredhubSecrets) Create(credhubSecret *credhubsecretv1.CredhubSecret) (result *credhubsecretv1.CredhubSecret, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(credhubsecretsResource, c.ns, credhubSecret), &credhubsecretv1.CredhubSecret{})

	if obj == nil {
		return nil, err
	}
	return obj.(*credhubsecretv1.CredhubSecret), err
}

// Update takes the representation of a credhubSecret and updates it. Returns the server's representation of the credhubSecret, and an error, if there is any.
func (c *FakeCredhubSecrets) Update(credhubSecret *credhubsecretv1.CredhubSecret) (result *credhubsecretv1.CredhubSecret, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(credhubsecretsResource, c.ns, credhubSecret), &credhubsecretv1.CredhubSecret{})

	if obj == nil {
		return nil, err
	}
	return obj.(*credhubsecretv1.CredhubSecret), err
}

// Delete takes name of the credhubSecret and deletes it. Returns an error if one occurs.
func (c *FakeCredhubSecrets) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(credhubsecretsResource, c.ns, name), &credhubsecretv1.CredhubSecret{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCredhubSecrets) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(credhubsecretsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &credhubsecretv1.CredhubSecretList{})
	return err
}

// Patch applies the patch and returns the patched credhubSecret.
func (c *FakeCredhubSecrets) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *credhubsecretv1.CredhubSecret, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(credhubsecretsResource, c.ns, name, data, subresources...), &credhubsecretv1.CredhubSecret{})

	if obj == nil {
		return nil, err
	}
	return obj.(*credhubsecretv1.CredhubSecret), err
}
