/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/ishustava/k8s-credhub-controller/pkg/apis/credhubsecret/v1"
	scheme "github.com/ishustava/k8s-credhub-controller/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CredhubSecretsGetter has a method to return a CredhubSecretInterface.
// A group's client should implement this interface.
type CredhubSecretsGetter interface {
	CredhubSecrets(namespace string) CredhubSecretInterface
}

// CredhubSecretInterface has methods to work with CredhubSecret resources.
type CredhubSecretInterface interface {
	Create(*v1.CredhubSecret) (*v1.CredhubSecret, error)
	Update(*v1.CredhubSecret) (*v1.CredhubSecret, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.CredhubSecret, error)
	List(opts metav1.ListOptions) (*v1.CredhubSecretList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.CredhubSecret, err error)
	CredhubSecretExpansion
}

// credhubSecrets implements CredhubSecretInterface
type credhubSecrets struct {
	client rest.Interface
	ns     string
}

// newCredhubSecrets returns a CredhubSecrets
func newCredhubSecrets(c *PivotalV1Client, namespace string) *credhubSecrets {
	return &credhubSecrets{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the credhubSecret, and returns the corresponding credhubSecret object, and an error if there is any.
func (c *credhubSecrets) Get(name string, options metav1.GetOptions) (result *v1.CredhubSecret, err error) {
	result = &v1.CredhubSecret{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("credhubsecrets").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CredhubSecrets that match those selectors.
func (c *credhubSecrets) List(opts metav1.ListOptions) (result *v1.CredhubSecretList, err error) {
	result = &v1.CredhubSecretList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("credhubsecrets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested credhubSecrets.
func (c *credhubSecrets) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("credhubsecrets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a credhubSecret and creates it.  Returns the server's representation of the credhubSecret, and an error, if there is any.
func (c *credhubSecrets) Create(credhubSecret *v1.CredhubSecret) (result *v1.CredhubSecret, err error) {
	result = &v1.CredhubSecret{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("credhubsecrets").
		Body(credhubSecret).
		Do().
		Into(result)
	return
}

// Update takes the representation of a credhubSecret and updates it. Returns the server's representation of the credhubSecret, and an error, if there is any.
func (c *credhubSecrets) Update(credhubSecret *v1.CredhubSecret) (result *v1.CredhubSecret, err error) {
	result = &v1.CredhubSecret{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("credhubsecrets").
		Name(credhubSecret.Name).
		Body(credhubSecret).
		Do().
		Into(result)
	return
}

// Delete takes name of the credhubSecret and deletes it. Returns an error if one occurs.
func (c *credhubSecrets) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("credhubsecrets").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *credhubSecrets) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("credhubsecrets").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched credhubSecret.
func (c *credhubSecrets) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.CredhubSecret, err error) {
	result = &v1.CredhubSecret{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("credhubsecrets").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
